# ext/avathar/bbguild/config/routing.yml
avathar_bbguild_00:
    path: /guild/{page}/{guild_id}
    defaults: { _controller: avathar.bbguild.controller:handleview , guild_id: 1, page: "welcome" }
    requirements:
        guild_id: \d*
        page: welcome|roster|achievements
avathar_bbguild_01:
    path: /getfaction
    defaults: { _controller:avathar.bbguild.admin.controller:getfaction}
avathar_bbguild_02:
    path: /getguildrank/{guild_id}
    defaults: { _controller:avathar.bbguild.admin.controller:getguildrank, guild_id: 1}
    requirements:
        guild_id: \d*
avathar_bbguild_03:
    path: /getplayerList/{game_id}
    defaults: { _controller:avathar.bbguild.admin.controller:getplayerList, game_id: "wow"}
avathar_bbguild_04:
    path: /getclassrace/{game_id}
    defaults: { _controller:avathar.bbguild.admin.controller:getclassrace, game_id: "wow"}