imports:
    - { resource: tables.yml }

# mapping of services to controller classes
services:
    avathar.bbguild.controller:
        class: avathar\bbguild\controller\view_controller
        arguments:
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '@dbal.conn'
            - '@ext.manager'
            - '@language'
            - '@pagination'
            - '@path_helper'
            - '@template'
            - '@request'
            - '@user'
            - '%avathar.bbguild.tables.bb_games%'
            - '%avathar.bbguild.tables.bb_logs%'
            - '%avathar.bbguild.tables.bb_ranks%'
            - '%avathar.bbguild.tables.bb_guild%'
            - '%avathar.bbguild.tables.bb_players%'
            - '%avathar.bbguild.tables.bb_classes%'
            - '%avathar.bbguild.tables.bb_races%'
            - '%avathar.bbguild.tables.bb_gameroles%'
            - '%avathar.bbguild.tables.bb_factions%'
            - '%avathar.bbguild.tables.bb_language%'
            - '%avathar.bbguild.tables.bb_motd%'
            - '%avathar.bbguild.tables.bb_recruit%'
            - '%avathar.bbguild.tables.bb_achievement_track%'
            - '%avathar.bbguild.tables.bb_achievement%'
            - '%avathar.bbguild.tables.bb_achievement_rewards%'
            - '%avathar.bbguild.tables.bb_criteria_track%'
            - '%avathar.bbguild.tables.bb_achievement_criteria%'
            - '%avathar.bbguild.tables.bb_relations_table%'
            - '%avathar.bbguild.tables.bb_bosstable%'
            - '%avathar.bbguild.tables.bb_zonetable%'
            - '%avathar.bbguild.tables.bb_news%'
            - '%avathar.bbguild.tables.bb_plugins%'
    avathar.bbguild.curl:
        class: avathar\bbguild\model\admin\curl
    avathar.bbguild.log:
        # bbguild logging class
        class: avathar\bbguild\model\admin\log
        arguments:
            - '%avathar.bbguild.tables.bb_logs%'
            - '@dbal.conn'
    avathar.bbguild.util:
        class: avathar\bbguild\model\admin\util
        arguments:
            - '@request'
    avathar.bbguild.admin.main:
        class: avathar\bbguild\controller\admin_main
        arguments:
            - '@auth'
            - '@cache.driver'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@pagination'
            - '@request'
            - '@template'
            - '@user'
            - '@path_helper'
            - '@ext.manager'
            - '%core.root_path%'
            - '%core.adm_relative_path%'
            - '%core.php_ext%'
            - '@avathar.bbguild.curl'
            - '@avathar.bbguild.log'
            - '@avathar.bbguild.util'
            - '%avathar.bbguild.tables.bb_games%'
            - '%avathar.bbguild.tables.bb_logs%'
            - '%avathar.bbguild.tables.bb_ranks%'
            - '%avathar.bbguild.tables.bb_guild%'
            - '%avathar.bbguild.tables.bb_players%'
            - '%avathar.bbguild.tables.bb_classes%'
            - '%avathar.bbguild.tables.bb_races%'
            - '%avathar.bbguild.tables.bb_gameroles%'
            - '%avathar.bbguild.tables.bb_factions%'
            - '%avathar.bbguild.tables.bb_language%'
            - '%avathar.bbguild.tables.bb_motd%'
            - '%avathar.bbguild.tables.bb_recruit%'
            - '%avathar.bbguild.tables.bb_achievement_track%'
            - '%avathar.bbguild.tables.bb_achievement%'
            - '%avathar.bbguild.tables.bb_achievement_rewards%'
            - '%avathar.bbguild.tables.bb_criteria_track%'
            - '%avathar.bbguild.tables.bb_achievement_criteria%'
            - '%avathar.bbguild.tables.bb_relations_table%'
            - '%avathar.bbguild.tables.bb_bosstable%'
            - '%avathar.bbguild.tables.bb_zonetable%'
            - '%avathar.bbguild.tables.bb_news%'
            - '%avathar.bbguild.tables.bb_plugins%'
    avathar.bbguild.listener:
        class: avathar\bbguild\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@config'
        tags:
            - { name: event.listener }
